version: '3'

services:
  teamserver:
    build: teamserver/
    ports:
      - "80:80"
    environment:
      - MODE=DEBUG
      - CELERY_BROKER_URL=amqp://arsenal_rabbitmq_1:5672
      - CELERY_RESULT_BACKEND=amqp://arsenal_rabbitmq_1:5672
      - DB_NAME=arsenal
      - DB_HOST=arsenal_mongo_1
      - DB_PORT=27017
      #- DB_USER=
      #- DB_PASS=password
      #- SLACK_ENABLED=True
      #- SLACK_API_TOKEN=None

  redis:
    image: redis

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq
